from pathlib import Path

p = Path('scientific-stewardship/index.html')
s = p.read_text(encoding='utf-8')

old_css = '.section-intro{margin:14px 0 0;max-width:820px;color:var(--text-dim);font-size:16px;line-height:1.72}'
new_css = old_css + '.story{max-width:900px}.story p{margin:0 0 18px;color:var(--text-dim);font-size:17px;line-height:1.78}.story p:last-child{margin-bottom:0}.story strong{color:var(--text)}.story-lead{font-size:20px!important;line-height:1.68!important;color:#dce8f2!important}.story-band{margin:28px 0;padding:24px 26px;border-left:3px solid var(--accent);background:var(--accent-soft);color:#dce8f2;font-size:16px;line-height:1.75}.story-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:28px 0}.story-step{padding:22px;border:1px solid var(--line);border-radius:12px;background:rgba(255,255,255,.02)}.story-step .num{color:var(--accent);font-size:11px;font-weight:800;letter-spacing:.12em;text-transform:uppercase}.story-step h3{margin:10px 0 8px;font-size:17px}.story-step p{margin:0;color:var(--text-dim);font-size:14px;line-height:1.65}.story-list{margin:18px 0 0;padding-left:20px}.story-list li{margin:0 0 10px;color:var(--text-dim);font-size:16px;line-height:1.7}@media(max-width:900px){.story-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.story-grid{grid-template-columns:1fr}}'
if old_css not in s:
    raise SystemExit('expected CSS anchor not found')
s = s.replace(old_css, new_css, 1)

start = s.index('<main>')
end = s.index('</main>') + len('</main>')

main = '''<main>
<section class="hero"><div class="wrap hero-grid"><div><div class="eyebrow"><span></span>Scientific Stewardship</div><h1>From model development to scientific stewardship.</h1><p class="hero-lede">The BAITSSS model began as a scientific effort to connect satellite observations with the water and energy balance that continues between overpasses. As the work matured into BAITSSS Desktop, the responsibility also became larger: not only to calculate a result, but to preserve how that result was produced, what evidence supports it, where uncertainty enters, and how far the interpretation can reasonably go.</p></div><aside class="hero-aside"><div class="label">The central idea</div><p>Scientific stewardship begins when the model result is treated as part of an evidence chain rather than as an isolated number or map.</p></aside></div></section>

<section class="section"><div class="wrap"><div class="section-head"><div class="section-kicker">01 · Why stewardship</div><div><h2>A model can calculate correctly and still be interpreted poorly.</h2></div></div><div class="story"><p class="story-lead">The BAITSSS model was developed to represent a continuously changing field system. Weather changes every hour. Vegetation develops through the season. Soil water is depleted and replenished. Energy exchange changes with atmospheric conditions, crop state, and water availability. Because each hour depends on the state carried from the hour before it, a final result is inseparable from the data, assumptions, and decisions that produced that trajectory.</p><p>That is why scientific stewardship is different from simply describing the equations. A scientifically responsible analysis must preserve the connection between <strong>what was observed, what was supplied, what the BAITSSS model calculated, what BAITSSS Desktop recorded, and what the researcher finally concluded</strong>.</p><p>As the earlier research implementation evolved into BAITSSS Desktop, this became increasingly important. A desktop system can make complex simulation easier to run, inspect, repeat, and export. That convenience is valuable, but it also increases the need to keep the scientific meaning of each quantity visible. A successful software run is not, by itself, scientific validation. A visually convincing map is not, by itself, evidence of accuracy. A modeled irrigation requirement is not automatically the irrigation actually applied in the field.</p><div class="story-band"><strong>Scientific stewardship is the discipline of keeping the scientific chain intact from source data to final conclusion.</strong></div></div></div></section>

<section class="section"><div class="wrap"><div class="section-head"><div class="section-kicker">02 · The evidence chain</div><div><h2>Four different kinds of information pass through a BAITSSS study.</h2></div></div><div class="story"><p>Many interpretation problems begin when different kinds of information are blended together. BAITSSS work is clearer when the scientific record remains separated into four classes.</p></div><div class="story-grid"><article class="story-step"><div class="num">Observed</div><h3>Measurements and observations</h3><p>Satellite measurements, field observations, weather measurements or forcing products, irrigation records, lysimeter data, eddy covariance, thermal observations, and other independent records retain their own measurement basis and uncertainty.</p></article><article class="story-step"><div class="num">Supplied</div><h3>Inputs and assumptions</h3><p>AOI, dates, soil properties, vegetation information, rooting depth, management assumptions, initial conditions, parameters, and other configured values define the simulation being asked of the BAITSSS model.</p></article><article class="story-step"><div class="num">Modeled</div><h3>Calculated states and fluxes</h3><p>ET components, surface and root-zone soil water, modeled irrigation, resistance behavior, and modeled soil and canopy temperatures are quantities calculated by the BAITSSS model.</p></article><article class="story-step"><div class="num">Concluded</div><h3>Scientific interpretation</h3><p>Statements about agreement, disagreement, field condition, management, performance, transferability, or applicability are conclusions. They are not direct model outputs.</p></article></div><div class="story"><p>The distinction matters because each class carries a different authority. An observation is not made more accurate because it is used by a model. A supplied parameter does not become an observation because it influences the result. A modeled variable does not become measured simply because it resembles a field value. And a scientific conclusion should never be presented as though it came directly from the model calculation.</p></div></div></section>

<section class="section"><div class="wrap"><div class="section-head"><div class="section-kicker">03 · What shapes the result</div><div><h2>Uncertainty enters before, during, and after model execution.</h2></div></div><div class="story"><p class="story-lead">A BAITSSS model result carries the influence of its forcing, vegetation representation, soil properties, initial water state, management assumptions, spatial scale, temporal matching, and model structure.</p><p>Weather forcing controls the atmospheric environment in which energy and water exchange are calculated. Satellite-derived vegetation information helps represent the evolving canopy. Soil hydraulic properties influence depletion, storage, evaporation, root-zone behavior, and irrigation response. Initial soil moisture determines where the simulated water balance begins. Management settings such as rooting depth and management allowable depletion alter how the modeled system responds to water stress and irrigation thresholds.</p><p>Those influences are not errors in themselves. They are part of the scientific representation. Stewardship means identifying them, preserving them, and testing their importance where the research question requires it.</p><p>Scale is equally important. A 30 m BAITSSS model pixel, a field average, a point soil-water measurement, an eddy-covariance footprint, a lysimeter, and a regional ET product do not represent exactly the same spatial support. Likewise, hourly, daily, seasonal, and annual quantities answer different questions. A comparison becomes stronger when those differences are acknowledged rather than hidden.</p></div></div></section>

<section class="section"><div class="wrap"><div class="section-head"><div class="section-kicker">04 · Reading the model correctly</div><div><h2>Model states describe the simulated field system.</h2></div></div><div class="story"><p><strong>Evapotranspiration.</strong> BAITSSS model ET comes from the coupled water and energy balance. Agreement with an independent ET observation or product is evidence for that particular comparison. It is not a universal accuracy statement.</p><p><strong>Soil water.</strong> Surface and root-zone soil-water states reflect the soil representation, initialization, precipitation, irrigation, evaporation, transpiration, and model structure used in that simulation. Their interpretation is therefore conditional on those choices.</p><p><strong>Irrigation.</strong> When the BAITSSS model simulates irrigation, the value represents irrigation required under the configured model rules. It should not be described as farmer-applied irrigation unless independent irrigation records establish that correspondence.</p><p><strong>Temperature.</strong> Soil and canopy temperatures are calculated internally by the BAITSSS model. Independent thermal measurements can be used for comparison, but measured thermal information and modeled temperature remain different evidence classes.</p><div class="story-band">The question is not only “What value did the model produce?” The stronger question is “What does this value represent in this simulation, and what evidence allows us to interpret it?”</div></div></div></section>

<section class="section"><div class="wrap"><div class="section-head"><div class="section-kicker">05 · Validation and verification</div><div><h2>Scientific validation and software verification protect different parts of the system.</h2></div></div><div class="story"><p>The BAITSSS model has been evaluated in peer-reviewed studies using independent field observations and comparison datasets. Those studies address scientific questions: how the model behaved at a defined site, during a defined period, under particular crops, climates, measurements, and input conditions.</p><p>BAITSSS Desktop introduces another responsibility. The software must also be shown to execute the intended science correctly. Numerical equivalence testing asks whether a changed execution route preserves the accepted scientific behavior. Software verification asks whether project state, data readiness, run identity, Stop and Resume, outputs, provenance, packaging, and related functions behave as intended.</p><p>These evidence classes complement each other, but they are not interchangeable. <strong>Software verification cannot substitute for field validation, and field validation cannot prove that every software pathway is implemented correctly.</strong></p><div class="cta-row"><a class="button button-primary" href="../origins-publications/#evidence">View Evidence</a><a class="button" href="../origins-publications/#published-studies">Published Studies</a></div></div></div></section>

<section class="section"><div class="wrap"><div class="section-head"><div class="section-kicker">06 · What BAITSSS Desktop adds</div><div><h2>The desktop should preserve the scientific context around the calculation.</h2></div></div><div class="story"><p class="story-lead">BAITSSS Desktop is not the scientific model. It is the maintained software environment that runs the BAITSSS model and keeps the project, data, configuration, execution, Results, and provenance connected.</p><p>That distinction is important because reproducibility depends on more than saving an output file. A defensible result should remain tied to the project and AOI, simulation period, BAITSSS Desktop build or version, model settings, data sources, input provenance, and the exact run that produced it.</p><p>Traceability allows a result to be revisited. It allows a collaborator to understand what was done. It allows numerical or scientific differences to be investigated instead of guessed at. It also makes clear when two simulations differ because of changed science, changed data, changed configuration, or changed software behavior.</p></div></div></section>

<section class="section"><div class="wrap"><div class="section-head"><div class="section-kicker">07 · Reporting a BAITSSS study</div><div><h2>A result should carry enough context to be examined by someone else.</h2></div></div><div class="story"><p>For research, education, collaboration, validation, or professional reporting, the scientific record should make the path from input to conclusion visible. At minimum, the study should identify:</p><ul class="story-list"><li>study area, AOI, and simulation dates;</li><li>satellite, weather, soil, terrain, land-cover, irrigation, and other material data sources;</li><li>initial conditions, management assumptions, rooting information, and material model settings;</li><li>the relevant BAITSSS model scientific references and the BAITSSS Desktop version or build used;</li><li>which quantities are observations, supplied inputs, model outputs, or externally derived comparison products;</li><li>the spatial and temporal basis used to compare model output with independent evidence;</li><li>known limitations, uncertainty, sensitivity, and conditions that restrict generalization.</li></ul><p>The purpose is not to burden every analysis with unnecessary detail. It is to preserve enough detail that the result can be understood, reproduced where possible, challenged where necessary, and improved when better data or methods become available.</p></div></div></section>

<section class="section"><div class="wrap"><div class="section-head"><div class="section-kicker">08 · Continuing stewardship</div><div><h2>Future capability should expand only with matching scientific accountability.</h2></div></div><div class="story"><p>The longer-term BAITSSS direction is broader than a single model run. Additional forcing routes, uncertainty analysis, forecasting, new observations, management applications, and decision-support functions may eventually make the scientific environment more useful. But each new capability changes the evidence chain and therefore creates new responsibilities for testing, validation, documentation, and interpretation.</p><p>For that reason, future development should not be judged only by whether BAITSSS Desktop can produce more outputs. It should also be judged by whether those outputs remain traceable to the BAITSSS model science, whether new assumptions are visible, whether changed execution is numerically verified where appropriate, and whether scientific claims remain proportional to the evidence.</p><div class="story-band"><strong>The goal of scientific stewardship is not to make every BAITSSS result unquestionable.</strong> It is to make the result understandable enough that it can be examined, reproduced, compared, challenged, and improved.</div><div class="cta-row"><a class="button button-primary" href="../science/">BAITSSS Model Science</a><a class="button" href="../origins-publications/">Scientific History &amp; Publications</a></div></div></div></section>
</main>'''

s = s[:start] + main + s[end:]
p.write_text(s, encoding='utf-8')
print('rewrote Scientific Stewardship as a narrative story')
